# Generated by Django 5.2.16 on 2026-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='comments/files/'),
        ),
    ]
